/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___color__H
#define ___color__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__color(Args *args);

pika_float _color_cmp_lux(PikaObj *self, int port, char* judgment, pika_float value);
pika_float _color_lux(PikaObj *self, int port);
pika_float _color_lux_state(PikaObj *self, int port);
void _color_one_calibrate(PikaObj *self, int port, int timers);
void _color_set_color_threshold_value(PikaObj *self, int port, int value);
void _color_two_calibrate(PikaObj *self, int port1, int port2, int timers);

#endif
