/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___key__H
#define ___key__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__key(Args *args);

int _key_key_mast(PikaObj *self, char* keyname, pika_float State);
int _key_key_remote(PikaObj *self, char* keys, char* coor);
int _key_read_adcance_left_offset(PikaObj *self);
int _key_read_advance_right_offset(PikaObj *self);
int _key_read_retreat_left_offset(PikaObj *self);
int _key_read_retreat_right_offset(PikaObj *self);

#endif
