/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___matrix__H
#define ___matrix__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__matrix(Args *args);

void _matrix_clear(PikaObj *self);
void _matrix_set_brightness(PikaObj *self, pika_float brigntness);
void _matrix_set_pixel(PikaObj *self, pika_float x, pika_float y);
void _matrix_set_pixel_brightness(PikaObj *self, pika_float x, pika_float y, pika_float brigntness);
void _matrix_show(PikaObj *self, pika_float bufer1, pika_float bufer2, pika_float bufer3, pika_float bufer4, pika_float bufer5, pika_float bufer6, pika_float bufer7);
void _matrix_show_roll(PikaObj *self, char* text);

#endif
