/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___motor__H
#define ___motor__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__motor(Args *args);

void _motor_mov_dir_power(PikaObj *self, char* dir, pika_float duty);
void _motor_mov_dir_power_seconds(PikaObj *self, char* dir, pika_float duty, pika_float degrees);
void _motor_mov_find_line_init(PikaObj *self);
void _motor_mov_find_line_run(PikaObj *self, pika_float gray_left, pika_float gray_right, pika_float power1, pika_float power2, pika_float kp, pika_float kd);
void _motor_mov_for_power_seconds(PikaObj *self, pika_float duty1, pika_float duty2, pika_float degrees);
void _motor_mov_power(PikaObj *self, pika_float duty1, pika_float duty2);
void _motor_mov_set_advance_offset(PikaObj *self, int offset1, int offset2);
void _motor_mov_set_retreat_offset(PikaObj *self, int offset1, int offset2);
void _motor_mov_set_stop_module(PikaObj *self, int mode);
void _motor_mov_stop(PikaObj *self);
void _motor_pair(PikaObj *self, int port1, int port2, int state);
void _motor_run_for_power_seconds(PikaObj *self, int port, pika_float duty, pika_float degrees);
void _motor_run_power(PikaObj *self, int port, pika_float duty);
void _motor_stop(PikaObj *self, int port);
void _motor_stop_module(PikaObj *self, int port, int stop);

#endif
