/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___os__H
#define ___os__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__os(Args *args);

int _os_get_port_linke(PikaObj *self, int port);
void _os_resetTimer(PikaObj *self);
void _os_sleep_s(PikaObj *self, pika_float tick);
void _os_stop_exit(PikaObj *self);
pika_float _os_timer(PikaObj *self);

#endif
