/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___ultrasion__H
#define ___ultrasion__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__ultrasion(Args *args);

int _ultrasion_cmp_value(PikaObj *self, int port, char* judgment, pika_float value);
pika_float _ultrasion_value(PikaObj *self, int port);

#endif
