def cmp_lux(port:int,judgment:str,value:float)->float:...

def lux(port:int)->float:...

def lux_state(port:int)->float:...

def two_calibrate(port1:int,port2:int,timers:int):...

def one_calibrate(port:int,timers:int):...

def set_color_threshold_value(port:int,value:int):...