def key_mast(keyname:str,State:float)->int:...	

def key_remote(keys:str,coor:str)->int:...

def read_adcance_left_offset()->int:...

def read_advance_right_offset()->int:...

def read_retreat_left_offset()->int:...

def read_retreat_right_offset()->int:...