def show(bufer1:float,bufer2:float,bufer3:float,bufer4:float,bufer5:float,bufer6:float,bufer7:float):...
	
def show_roll(text:str):...
	
def set_brightness(brigntness:float):...
	
def set_pixel(x:float , y:float):...
	
def set_pixel_brightness(x:float , y:float , brigntness:float):...
	
def clear():...