def run_for_power_seconds(port:int,duty:float,degrees:float):...

def run_power(port:int,duty:float):...

def stop(port:int):...

def stop_module(port:int,stop:int):...

def pair(port1:int,port2:int,state:int):...

def mov_set_stop_module(mode:int):...

def mov_dir_power_seconds(dir:str,duty:float,degrees:float):...

def mov_dir_power(dir:str,duty:float):...

def mov_stop():...

def mov_for_power_seconds(duty1:float,duty2:float,degrees:float):...

def mov_power(duty1:float,duty2:float):...

def mov_find_line_init():...

def mov_find_line_run(gray_left:float,gray_right:float,power1:float,power2:float,kp:float,kd:float):...

def mov_set_advance_offset(offset1:int,offset2:int):...

def mov_set_retreat_offset(offset1:int,offset2:int):...